services:
  frps:
    build: .
    container_name: frps-server
    restart: always
    ports:
      - '7000:7000'
    environment:
      - FRP_SERVER_TOKEN=${FRP_SERVER_TOKEN}
    labels:
      - traefik.enable=true
      # Eliminamos la línea de entrypoints para que Traefik no dé error
      - "traefik.http.routers.frp-final.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.tunnels.digitalprojex.site`)"
      - "traefik.http.routers.frp-final.tls=true"
      - "traefik.http.routers.frp-final.tls.certresolver=letsencrypt"
      
      # Servicio (Asegúrate de que el nombre sea único)
      - "traefik.http.routers.frp-final.service=frp-final-svc"
      - "traefik.http.services.frp-final-svc.loadbalancer.server.port=7075"
      - "traefik.http.services.frp-final-svc.loadbalancer.passhostheader=true"
    networks:
      - coolify

networks:
  coolify:
    external: true
