services:
  frps:
    build: .
    container_name: frps-server
    restart: always

    ports:
      - "7000:7000"

    environment:
      - "FRP_SERVER_TOKEN=${FRP_SERVER_TOKEN}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frp-v3.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.tunnels.digitalprojex.site`)"
      - "traefik.http.routers.frp-v3.entrypoints=web"
      - "traefik.http.routers.frp-v3.priority=10000"
      - "traefik.http.routers.frp-v3.service=frp-v3-svc"
      - "traefik.http.services.frp-v3-svc.loadbalancer.server.port=7075"
      - "traefik.http.services.frp-v3-svc.loadbalancer.passhostheader=true"

    networks:
      - coolify

networks:
  coolify:
    external: true
